/*
 * This source file was generated by the Gradle 'init' task
 */
package io.grandine;

import org.junit.Test;
import static org.junit.Assert.*;

public class GrandineTest {
    @Test public void initialization() {
        // FIXME: fix error due to https://github.com/jemalloc/jemalloc/issues/1237
        Grandine grandine = new Grandine();
    }
}
