[package]
name = 'pubkey_cache'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bls = { workspace = true }
dashmap = { workspace = true }
database = { workspace = true }
log = { workspace = true }
ssz = { workspace = true }
std_ext = { workspace = true }
typenum = { workspace = true }
types = { workspace = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
prometheus_metrics = { workspace = true }
tynm = { workspace = true }

[dev-dependencies]
bytesize = { workspace = true }
eth2_cache_utils = { workspace = true }
hex-literal = { workspace = true }
tempfile = { workspace = true }

[features]
eth2-cache = []
