/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_grandine_Grandine */

#ifndef _Included_io_grandine_Grandine
#define _Included_io_grandine_Grandine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_grandine_Grandine
 * Method:    run
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_grandine_Grandine_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
