[package]
name = 'validator_key_cache'
version = '0.1.0'
edition.workspace = true
authors = ["Grandine <info@grandine.io>"]

[dependencies]
anyhow = { workspace = true }
bls = { workspace = true }
eip_2335 = { workspace = true }
fs-err = { workspace = true }
logging = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
ssz = { workspace = true }
tap = { workspace = true }
tracing = { workspace = true }
try_from_iterator = { workspace = true }
typenum = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }

[lints]
workspace = true
