[package]
name = 'ssz'
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
arithmetic = { workspace = true }
bit_field = { workspace = true }
bitvec = { workspace = true }
byteorder = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
easy-ext = { workspace = true }
ethereum-types = { workspace = true }
generic-array = { workspace = true }
hashing = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
once_cell = { workspace = true }
primitive-types = { workspace = true }
replace_with = { workspace = true }
serde = { workspace = true }
serde_utils = { workspace = true }
ssz_derive = { workspace = true }
static_assertions = { workspace = true }
std_ext = { workspace = true }
tap = { workspace = true }
thiserror = { workspace = true }
triomphe = { workspace = true }
try_from_iterator = { workspace = true }
typenum = { workspace = true }

[dev-dependencies]
duplicate = { workspace = true }
spec_test_utils = { workspace = true }
test-case = { workspace = true }
test-generator = { workspace = true }
