// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Grandine.Native
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "grandine";

        public const uint GRANDINE_SUCCESS = 0;
        public const uint GRANDINE_ERROR_GENERIC = 1;
        public const uint GRANDINE_ERROR_ENGINE_API = 2;




        [DllImport(__DllName, EntryPoint = "grandine_set_execution_layer_adapter", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CResult_u8 grandine_set_execution_layer_adapter(CEmbedAdapter adapter);

        [DllImport(__DllName, EntryPoint = "grandine_alloc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* grandine_alloc(System.UIntPtr size);

        /// <summary>
        ///  Copies string to a pointer managed by grandine.
        ///  CErrorMessage must be passed back to grandine, where it will be automatically cleaned up.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "grandine_error_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CErrorMessage grandine_error_message(byte* str_);

        [DllImport(__DllName, EntryPoint = "grandine_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void grandine_shutdown();

        [DllImport(__DllName, EntryPoint = "grandine_run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong grandine_run(ulong argc, byte** argv);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CErrorMessage
    {
        public byte* _0;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_u8
    {
        public byte value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH256
    {
        public fixed byte _0[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CH256
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CH256 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadStatusV1
    {
        public CPayloadValidationStatus status;
        public COption_CH256 latest_valid_hash;
        public CErrorMessage validation_error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CPayloadStatusV1
    {
        public CPayloadStatusV1 value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH160
    {
        public fixed byte _0[20];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_u8
    {
        public byte* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CTransaction
    {
        public CVec_u8 _0;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_CTransaction
    {
        public CTransaction* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionPayloadV1
    {
        public CH256 parent_hash;
        public CH160 fee_recipient;
        public CH256 state_root;
        public CH256 receipts_root;
        public CVec_u8 logs_bloom;
        public CH256 prev_randao;
        public ulong block_number;
        public ulong gas_limit;
        public ulong gas_used;
        public ulong timestamp;
        public CVec_u8 extra_data;
        public CH256 base_fee_per_gas;
        public CH256 block_hash;
        public CVec_CTransaction transactions;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CWithdrawalV1
    {
        public ulong index;
        public ulong validator_index;
        public CH160 address;
        public ulong amount;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_CWithdrawalV1
    {
        public CWithdrawalV1* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionPayloadV2
    {
        public CH256 parent_hash;
        public CH160 fee_recipient;
        public CH256 state_root;
        public CH256 receipts_root;
        public CVec_u8 logs_bloom;
        public CH256 prev_randao;
        public ulong block_number;
        public ulong gas_limit;
        public ulong gas_used;
        public ulong timestamp;
        public CVec_u8 extra_data;
        public CH256 base_fee_per_gas;
        public CH256 block_hash;
        public CVec_CTransaction transactions;
        public CVec_CWithdrawalV1 withdrawals;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionPayloadV3
    {
        public CH256 parent_hash;
        public CH160 fee_recipient;
        public CH256 state_root;
        public CH256 receipts_root;
        public CVec_u8 logs_bloom;
        public CH256 prev_randao;
        public ulong block_number;
        public ulong gas_limit;
        public ulong gas_used;
        public ulong timestamp;
        public CVec_u8 extra_data;
        public CH256 base_fee_per_gas;
        public CH256 block_hash;
        public CVec_CTransaction transactions;
        public CVec_CWithdrawalV1 withdrawals;
        public ulong blob_gas_used;
        public ulong excess_blob_gas;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_CH256
    {
        public CH256* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_CVec_u8
    {
        public CVec_u8* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionRequests
    {
        public CVec_CVec_u8 _0;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH64
    {
        public fixed byte _0[8];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CH64
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CH64 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CForkChoiceUpdatedResponse
    {
        public CPayloadStatusV1 payload_status;
        public COption_CH64 payload_id;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CForkChoiceUpdatedResponse
    {
        public CForkChoiceUpdatedResponse value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CForkChoiceStateV1
    {
        public CH256 head_block_hash;
        public CH256 safe_block_hash;
        public CH256 finalized_block_hash;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadAttributesV1
    {
        public ulong timestamp;
        public CH256 prev_randao;
        public CH160 suggested_fee_recipient;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CPayloadAttributesV1
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CPayloadAttributesV1 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadAttributesV2
    {
        public ulong timestamp;
        public CH256 prev_randao;
        public CH160 suggested_fee_recipient;
        public CVec_CWithdrawalV1 withdrawals;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CPayloadAttributesV2
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CPayloadAttributesV2 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadAttributesV3
    {
        public ulong timestamp;
        public CH256 prev_randao;
        public CH160 suggested_fee_recipient;
        public CVec_CWithdrawalV1 withdrawals;
        public CH256 parent_beacon_block_root;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CPayloadAttributesV3
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CPayloadAttributesV3 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CExecutionPayloadV1
    {
        public CExecutionPayloadV1 value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV2Response
    {
        public CExecutionPayloadV2 execution_payload;
        public CH256 block_value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CEngineGetPayloadV2Response
    {
        public CEngineGetPayloadV2Response value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH384
    {
        public fixed byte _0[48];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_CH384
    {
        public CH384* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CBlobsBundleV1
    {
        public CVec_CH384 commitments;
        public CVec_CH384 proofs;
        public CVec_CVec_u8 blobs;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV3Response
    {
        public CExecutionPayloadV3 execution_payload;
        public CH256 block_value;
        public CBlobsBundleV1 blobs_bundle;
        [MarshalAs(UnmanagedType.U1)] public bool should_override_builder;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CEngineGetPayloadV3Response
    {
        public CEngineGetPayloadV3Response value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV4Response
    {
        public CExecutionPayloadV3 execution_payload;
        public CH256 block_value;
        public CBlobsBundleV1 blobs_bundle;
        [MarshalAs(UnmanagedType.U1)] public bool should_override_builder;
        public CExecutionRequests execution_requests;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CEngineGetPayloadV4Response
    {
        public CEngineGetPayloadV4Response value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV5Response
    {
        public CExecutionPayloadV3 execution_payload;
        public CH256 block_value;
        public CBlobsBundleV1 blobs_bundle;
        [MarshalAs(UnmanagedType.U1)] public bool should_override_builder;
        public CExecutionRequests execution_requests;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CEngineGetPayloadV5Response
    {
        public CEngineGetPayloadV5Response value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CBlobAndProofV1
    {
        public CH384 proof;
        public CVec_u8 blob;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CBlobAndProofV1
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CBlobAndProofV1 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_COption_CBlobAndProofV1
    {
        public COption_CBlobAndProofV1* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_CVec_COption_CBlobAndProofV1
    {
        public CVec_COption_CBlobAndProofV1 value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CBlobAndProofV2
    {
        public CVec_CH384 proof;
        public CVec_u8 blob;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVec_CBlobAndProofV2
    {
        public CBlobAndProofV2* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COption_CVec_CBlobAndProofV2
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CVec_CBlobAndProofV2 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResult_COption_CVec_CBlobAndProofV2
    {
        public COption_CVec_CBlobAndProofV2 value;
        public uint code;
        public CErrorMessage message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEmbedAdapter
    {
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV1, CResult_CPayloadStatusV1> engine_new_payload_v1;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV2, CResult_CPayloadStatusV1> engine_new_payload_v2;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV3, CVec_CH256, CH256, CResult_CPayloadStatusV1> engine_new_payload_v3;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV3, CVec_CH256, CH256, CExecutionRequests, CResult_CPayloadStatusV1> engine_new_payload_v4;
        public delegate* unmanaged[Cdecl]<CForkChoiceStateV1, COption_CPayloadAttributesV1, CResult_CForkChoiceUpdatedResponse> engine_forkchoice_updated_v1;
        public delegate* unmanaged[Cdecl]<CForkChoiceStateV1, COption_CPayloadAttributesV2, CResult_CForkChoiceUpdatedResponse> engine_forkchoice_updated_v2;
        public delegate* unmanaged[Cdecl]<CForkChoiceStateV1, COption_CPayloadAttributesV3, CResult_CForkChoiceUpdatedResponse> engine_forkchoice_updated_v3;
        public delegate* unmanaged[Cdecl]<CH64, CResult_CExecutionPayloadV1> engine_get_payload_v1;
        public delegate* unmanaged[Cdecl]<CH64, CResult_CEngineGetPayloadV2Response> engine_get_payload_v2;
        public delegate* unmanaged[Cdecl]<CH64, CResult_CEngineGetPayloadV3Response> engine_get_payload_v3;
        public delegate* unmanaged[Cdecl]<CH64, CResult_CEngineGetPayloadV4Response> engine_get_payload_v4;
        public delegate* unmanaged[Cdecl]<CH64, CResult_CEngineGetPayloadV5Response> engine_get_payload_v5;
        public delegate* unmanaged[Cdecl]<CVec_CH256, CResult_CVec_COption_CBlobAndProofV1> engine_get_blobs_v1;
        public delegate* unmanaged[Cdecl]<CVec_CH256, CResult_COption_CVec_CBlobAndProofV2> engine_get_blobs_v2;
    }


    public enum CPayloadValidationStatus : uint
    {
        Valid = 0,
        Invalid = 1,
        Syncing = 2,
        Accepted = 3,
        InvalidBlockHash = 4,
    }


}
