// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Grandine.Native
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "c_grandine";



        [DllImport(__DllName, EntryPoint = "grandine_set_execution_layer_adapter", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void grandine_set_execution_layer_adapter(CEmbedAdapter adapter);

        [DllImport(__DllName, EntryPoint = "grandine_run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong grandine_run(ulong argc, byte** argv);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultU64
    {
        public ulong value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCOptionCEth1Block
    {
        public COptionCEth1Block value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCLogs
    {
        public CLogs value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCPayloadStatusV1
    {
        public CPayloadStatusV1 value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCForkChoiceUpdatedResponse
    {
        public CForkChoiceUpdatedResponse value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCExecutionPayloadV1
    {
        public CExecutionPayloadV1 value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCEngineGetPayloadV2Response
    {
        public CEngineGetPayloadV2Response value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCEngineGetPayloadV3Response
    {
        public CEngineGetPayloadV3Response value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCEngineGetPayloadV4Response
    {
        public CEngineGetPayloadV4Response value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEth1Block
    {
        public fixed byte hash[32];
        public fixed byte parent_hash[32];
        public ulong number;
        public ulong timestamp;
        public fixed byte total_difficulty[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CTransaction
    {
        public byte* bytes;
        public ulong bytes_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionPayloadV1
    {
        public fixed byte parent_hash[32];
        public fixed byte fee_recipient[20];
        public fixed byte state_root[32];
        public fixed byte receipts_root[32];
        public byte* logs_bloom;
        public ulong logs_bloom_len;
        public fixed byte prev_randao[32];
        public ulong block_number;
        public ulong gas_limit;
        public ulong gas_used;
        public ulong timestamp;
        public byte* extra_data;
        public ulong extra_data_len;
        public fixed byte base_fee_per_gas[32];
        public fixed byte block_hash[32];
        public CTransaction* transactions;
        public ulong transactions_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CWithdrawalV1
    {
        public ulong index;
        public ulong validator_index;
        public fixed byte address[20];
        public ulong amount;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionPayloadV2
    {
        public fixed byte parent_hash[32];
        public fixed byte fee_recipient[20];
        public fixed byte state_root[32];
        public fixed byte receipts_root[32];
        public byte* logs_bloom;
        public ulong logs_bloom_len;
        public fixed byte prev_randao[32];
        public ulong block_number;
        public ulong gas_limit;
        public ulong gas_used;
        public ulong timestamp;
        public byte* extra_data;
        public ulong extra_data_len;
        public fixed byte base_fee_per_gas[32];
        public fixed byte block_hash[32];
        public CTransaction* transactions;
        public ulong transactions_len;
        public CWithdrawalV1* withdrawals;
        public ulong withdrawals_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionPayloadV3
    {
        public fixed byte parent_hash[32];
        public fixed byte fee_recipient[20];
        public fixed byte state_root[32];
        public fixed byte receipts_root[32];
        public byte* logs_bloom;
        public ulong logs_bloom_len;
        public fixed byte prev_randao[32];
        public ulong block_number;
        public ulong gas_limit;
        public ulong gas_used;
        public ulong timestamp;
        public byte* extra_data;
        public ulong extra_data_len;
        public fixed byte base_fee_per_gas[32];
        public fixed byte block_hash[32];
        public CTransaction* transactions;
        public ulong transactions_len;
        public CWithdrawalV1* withdrawals;
        public ulong withdrawals_len;
        public ulong blob_gas_used;
        public ulong excess_blob_gas;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH384
    {
        public fixed byte Item1[48];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH256
    {
        public fixed byte Item1[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCH256
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CH256 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCH64
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CH64 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionU64
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public ulong value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCVecCH160
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CVecCH160 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCVecCH256
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CVecCH256 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCVecCOptionCVecCH256
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CVecCOptionCVecCH256 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCStr
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CCharPtr value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CCharPtr
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionBool
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        [MarshalAs(UnmanagedType.U1)] public bool value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCEth1Block
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CEth1Block value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCPayloadAttributesV1
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CPayloadAttributesV1 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCPayloadAttributesV2
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CPayloadAttributesV2 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCPayloadAttributesV3
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CPayloadAttributesV3 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadStatusV1
    {
        public CPayloadValidationStatus status;
        public COptionCH256 latest_valid_hash;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CForkChoiceStateV1
    {
        public fixed byte head_block_hash[32];
        public fixed byte safe_block_hash[32];
        public fixed byte finalized_block_hash[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadAttributesV1
    {
        public ulong timestamp;
        public fixed byte prev_randao[32];
        public fixed byte suggested_fee_recipient[20];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadAttributesV2
    {
        public ulong timestamp;
        public fixed byte prev_randao[32];
        public fixed byte suggested_fee_recipient[20];
        public CWithdrawalV1* withdrawals;
        public ulong withdrawals_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CPayloadAttributesV3
    {
        public ulong timestamp;
        public fixed byte prev_randao[32];
        public fixed byte suggested_fee_recipient[20];
        public CWithdrawalV1* withdrawals;
        public ulong withdrawals_len;
        public fixed byte parent_beacon_block_root[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH64
    {
        public fixed byte Item1[8];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CForkChoiceUpdatedResponse
    {
        public CPayloadStatusV1 payload_status;
        public COptionCH64 payload_id;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CRequest
    {
        public byte* bytes;
        public ulong bytes_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecutionRequests
    {
        public CRequest* requests;
        public ulong requests_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CBlobAndProofV1
    {
        public CH384 proof;
        public byte* blob;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct COptionCBlobAndProofV1
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_something;
        public CBlobAndProofV1 value;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVecCOptionCBlobAndProofV1
    {
        public COptionCBlobAndProofV1* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CResultCVecCOptionCBlobAndProofV1
    {
        public CVecCOptionCBlobAndProofV1 value;
        public ulong error;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV2Response
    {
        public CExecutionPayloadV2 execution_payload;
        public fixed byte block_value[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CBlobsBundleV1
    {
        public byte** commitments;
        public ulong commitments_len;
        public byte** proofs;
        public ulong proofs_len;
        public byte** blobs;
        public ulong blobs_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV3Response
    {
        public CExecutionPayloadV3 execution_payload;
        public fixed byte block_value[32];
        public CBlobsBundleV1 blobs_bundle;
        [MarshalAs(UnmanagedType.U1)] public bool should_override_builder;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEngineGetPayloadV4Response
    {
        public CExecutionPayloadV3 execution_payload;
        public fixed byte block_value[32];
        public CBlobsBundleV1 blobs_bundle;
        [MarshalAs(UnmanagedType.U1)] public bool should_override_builder;
        public CExecutionRequests execution_requests;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CH160
    {
        public fixed byte Item1[20];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CFilter
    {
        public COptionU64 from_block;
        public COptionU64 to_block;
        public COptionCVecCH160 address;
        public COptionCVecCOptionCVecCH256 topics;
        public COptionU64 limit;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVecCH160
    {
        public CH160* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVecCH256
    {
        public CH256* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVecCOptionCVecCH256
    {
        public COptionCVecCH256* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CVecU8
    {
        public byte* data;
        public ulong data_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CLog
    {
        public fixed byte address[20];
        public CVecCH256 topics;
        public CVecU8 data;
        public COptionCH256 block_hash;
        public COptionU64 block_number;
        public COptionCH256 transaction_hash;
        public COptionU64 transaction_index;
        public COptionCH256 log_index;
        public COptionCH256 transaction_log_index;
        public COptionCStr log_type;
        public COptionBool removed;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CLogs
    {
        public CLog* logs;
        public ulong logs_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEmbedAdapter
    {
        public delegate* unmanaged[Cdecl]<CResultU64> eth_block_number;
        public delegate* unmanaged[Cdecl]<CH256, CResultCOptionCEth1Block> eth_get_block_by_hash;
        public delegate* unmanaged[Cdecl]<ulong, CResultCOptionCEth1Block> eth_get_block_by_number;
        public delegate* unmanaged[Cdecl]<CResultCOptionCEth1Block> eth_get_block_finalized;
        public delegate* unmanaged[Cdecl]<CResultCOptionCEth1Block> eth_get_block_safe;
        public delegate* unmanaged[Cdecl]<CResultCOptionCEth1Block> eth_get_block_latest;
        public delegate* unmanaged[Cdecl]<CResultCOptionCEth1Block> eth_get_block_earliest;
        public delegate* unmanaged[Cdecl]<CResultCOptionCEth1Block> eth_get_block_pending;
        public delegate* unmanaged[Cdecl]<CFilter, CResultCLogs> eth_logs;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV1, CResultCPayloadStatusV1> engine_new_payload_v1;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV2, CResultCPayloadStatusV1> engine_new_payload_v2;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV3, byte**, ulong, byte*, CResultCPayloadStatusV1> engine_new_payload_v3;
        public delegate* unmanaged[Cdecl]<CExecutionPayloadV3, byte**, ulong, byte*, CExecutionRequests, CResultCPayloadStatusV1> engine_new_payload_v4;
        public delegate* unmanaged[Cdecl]<CForkChoiceStateV1, COptionCPayloadAttributesV1, CResultCForkChoiceUpdatedResponse> engine_forkchoice_updated_v1;
        public delegate* unmanaged[Cdecl]<CForkChoiceStateV1, COptionCPayloadAttributesV2, CResultCForkChoiceUpdatedResponse> engine_forkchoice_updated_v2;
        public delegate* unmanaged[Cdecl]<CForkChoiceStateV1, COptionCPayloadAttributesV3, CResultCForkChoiceUpdatedResponse> engine_forkchoice_updated_v3;
        public delegate* unmanaged[Cdecl]<byte*, CResultCExecutionPayloadV1> engine_get_payload_v1;
        public delegate* unmanaged[Cdecl]<byte*, CResultCEngineGetPayloadV2Response> engine_get_payload_v2;
        public delegate* unmanaged[Cdecl]<byte*, CResultCEngineGetPayloadV3Response> engine_get_payload_v3;
        public delegate* unmanaged[Cdecl]<byte*, CResultCEngineGetPayloadV4Response> engine_get_payload_v4;
        public delegate* unmanaged[Cdecl]<byte**, ulong, CResultCVecCOptionCBlobAndProofV1> engine_get_blobs_v1;
    }


    public enum CPayloadValidationStatus : byte
    {
        Valid = 0,
        Invalid,
        Syncing,
        Accepted,
        InvalidBlockHash,
    }


}
