[package]
name = "bls-arkworks"
edition = { workspace = true }

[dependencies]
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
bls-core = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
fixed-hash = { workspace = true }
itertools = { workspace = true }
impl-serde = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_utils = { workspace = true }
sha2 = { workspace = true }
ssz = { workspace = true }
static_assertions = { workspace = true }
typenum = { workspace = true }
zeroize = { workspace = true }