{
 "title": "Attestation",
 "time": { "from": "2023-08-31T13:58:22.661Z", "to": "2023-08-31T14:39:03.046Z" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  { "title": "Attestation Verifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Task Count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ATTESTATION_VERIFIER_ACTIVE_TASK_COUNT{instance=~\"$Instance\"}"
    },
    {
     "expr": "rate(ATTESTATION_VERIFIER_ACTIVE_TASK_COUNT{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "AVG {{label_name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Process Aggregate Batch times (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ATTESTATION_VERIFIER_PROCESS_AGGREGATE_BATCH_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ATTESTATION_VERIFIER_PROCESS_AGGREGATE_BATCH_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Process Attestation Batch (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ATTESTATION_VERIFIER_PROCESS_ATTESTATION_BATCH_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ATTESTATION_VERIFIER_PROCESS_ATTESTATION_BATCH_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Verify Aggregate Batch Signature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ATTESTATION_VERIFIER_VERIFY_AGG_BATCH_SIGNATURES_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ATTESTATION_VERIFIER_VERIFY_AGG_BATCH_SIGNATURES_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Mutator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Attestation Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(MUTATOR_ATTESTATIONS{type=\"accepted\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Accepted ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_ATTESTATIONS{type=\"ignored\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Ignored ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_ATTESTATIONS{type=\"rejected\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Rejected ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_ATTESTATIONS{type=\"delayed_until_slot\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Delayed until slot ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_ATTESTATIONS{type=\"delayed_until_block\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Delayed until block ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_ATTESTATIONS{type=\"delayed_until_state\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Delayed until state ({{instance}})"
    }
   ]
  },
  {
   "title": "Aggregate And Proof Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(MUTATOR_AGGREGATE_AND_PROOFS{type=\"accepted\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Accepted ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_AGGREGATE_AND_PROOFS{type=\"ignored\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Ignored ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_AGGREGATE_AND_PROOFS{type=\"rejected\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Rejected ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_AGGREGATE_AND_PROOFS{type=\"delayed_until_block\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Delayed until block ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_AGGREGATE_AND_PROOFS{type=\"delayed_until_slot\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Delayed until slot ({{instance}})"
    },
    {
     "expr": "rate(MUTATOR_AGGREGATE_AND_PROOFS{type=\"delayed_until_state\",instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "Delayed until state ({{instance}})"
    }
   ]
  },
  {
   "title": "Attestation metrics from Validator Client ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Validator Attest tick avg times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_ATTEST_TICK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_ATTEST_TICK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Validator Aggregate tick avg times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_AGGREGATE_TICK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_AGGREGATE_TICK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Owned attestations init avg times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_OWN_ATTESTATIONS_INIT_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_OWN_ATTESTATIONS_INIT_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slashing protector attestation AVG times ",
   "type": "timeseries",
   "description": "Checking attestations for slashing violations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_ATTEST_SLASHING_PROTECTOR_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_ATTEST_SLASHING_PROTECTOR_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator attestation duty AVG times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_ATTEST_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_ATTEST_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation metrics from HTTP API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "HTTP API Attestation data AVG times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_API_ATTESTATION_DATA_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_API_ATTESTATION_DATA_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP API Attestation data request counts (avg rounded)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(VALIDATOR_API_ATTESTATION_DATA_TIMES_count{instance=~\"$Instance\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}