{
 "title": "Grandine Fork Choice / Mutator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "FC tasks / Validations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FC BlockAttestation Task times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_BLOCK_ATTESTATION_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_BLOCK_ATTESTATION_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC Attestation Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_ATTESTATION_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_ATTESTATION_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC Block Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_BLOCK_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_BLOCK_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC AggregateAndProof Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_AGGREGATE_AND_PROOF_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_AGGREGATE_AND_PROOF_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC PreprocessState task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_PREPROCESS_STATE_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_PREPROCESS_STATE_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC Checkpoint State Task ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_CHECKPOINT_STATE_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_CHECKPOINT_STATE_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC persist pubkey cache task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_PERSIST_PUBKEY_CACHE_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_PERSIST_PUBKEY_CACHE_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "FC Attester Slashing Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(FC_ATTESTER_SLASHING_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(FC_ATTESTER_SLASHING_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  { "title": "Mutator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Block inserting times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(MUTATOR_BLOCK_INSERTION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(MUTATOR_BLOCK_INSERTION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Block processing times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(MUTATOR_BLOCK_PROCESSING_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(MUTATOR_BLOCK_PROCESSING_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Block post processing times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(MUTATOR_BLOCK_POST_PROCESSING_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(MUTATOR_BLOCK_POST_PROCESSING_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  }
 ]
}