{
 "title": "Grandine HTTP API Response times",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  {
   "title": "Longest response times ",
   "type": "timeseries",
   "description": "99th percentile HTTP API response times",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(HTTP_API_RESPONSE_TIMES_bucket{instance=~\"$Instance\"}[$__rate_interval])))",
     "legendFormat": "{{request_path}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average response times",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(HTTP_API_RESPONSE_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval])) /  (rate(HTTP_API_RESPONSE_TIMES_count{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{request_path}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average request counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(HTTP_API_RESPONSE_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{request_path}} ({{instance}})"
    }
   ]
  }
 ]
}