{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grandine Liveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "IS_LIVE{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Clock Slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_slot{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_head_slot{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Finalized epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "CORE_COUNT{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "System Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SYSTEM_TOTAL_MEMORY{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Grandine Total CPU load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "GRANDINE_TOTAL_CPU_PERCENTAGE{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "System CPU load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "SYSTEM_CPU_PERCENTAGE{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Grandine Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "GRANDINE_USED_MEMORY{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "System Used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "SYSTEM_USED_MEMORY{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Grandine vs Lighthouse CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "GRANDINE_TOTAL_CPU_PERCENTAGE{instance=~\"$Instance\"}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$Instance\"}[$__rate_interval]) * 100",
     "legendFormat": "process_cpu_seconds_total {{label_name}} {{instance}}"
    },
    {
     "expr": "rate(GRANDINE_TOTAL_CPU_SECONDS{instance=~\"$Instance\"}[$__rate_interval]) * 100",
     "legendFormat": "GRANDINE_TOTAL_CPU_SECONDS {{instance}}"
    }
   ]
  },
  {
   "title": "Grandine Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "GRANDINE_THREAD_COUNT{instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dedicated Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(DEDICATED_EXECUTOR_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(DEDICATED_EXECUTOR_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
      }
     ]
    },
    {
     "title": "Task count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "DEDICATED_EXECUTOR_TASK_COUNT{instance=~\"$Instance\"}"
      }
     ]
    },
    {
     "title": "Dedicated Executor Thread count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DEDICATED_EXECUTOR_THREAD_COUNT{instance=~\"$Instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Jemalloc Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total number of bytes allocated by the application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "JEMALLOC_BYTES_ALLOCATED{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total number of bytes in active pages allocated by the application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "JEMALLOC_BYTES_ACTIVE{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total number of bytes dedicated to `jemalloc` metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "JEMALLOC_BYTES_METADATA{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total number of bytes in physically resident data pages mapped by the allocator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "JEMALLOC_BYTES_RESIDENT{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total number of bytes in active extents mapped by the allocator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "JEMALLOC_BYTES_MAPPED{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total number of bytes in virtual memory mappings that were retained rather than being returned to the OS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "JEMALLOC_BYTES_RETAINED{instance=~\"$Instance\"}"
    }
   ]
  },
  { "title": "Collection Lengths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Collection Lengths",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\"}",
     "legendFormat": "{{name}} ({{type}} {{instance}})"
    }
   ]
  },
  { "title": "Network Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Node received bytes avg.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(NODE_RX_BYTES{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Node Sent bytes avg.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(NODE_TX_BYTES{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "GRANDINE_DISK_USAGE{instance=~\"$Instance\"}"
    }
   ]
  },
  { "title": "Chain Info / EF metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Justified Epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Safe Head Slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_head_slot{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_active_validators{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Beacon Processed deposits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "beacon_processed_deposits_total{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Beacon reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 124 },
   "targets": [
    {
     "expr": "rate(beacon_reorgs_total{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Validator Count",
   "type": "stat",
   "description": "Number of total validators",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Prev Epoch Active Gwei Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_active_gwei_total{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Prev Epoch Target Attesting Gwei total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attesting_gwei_total{instance=~\"$Instance\"}"
    }
   ]
  }
 ]
}