{
 "title": "PeerDAS metrics",
 "description": "Beacon PeerDAS metrics according to the beacon metrics specs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data column sidecars submitted for processing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " avg_over_time(increase(beacon_data_column_sidecar_processing_requests_total{instance=~\"$Instance\"}[$__interval])[1m:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data column sidecars verified for gossip",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " avg_over_time(increase(beacon_data_column_sidecar_processing_successes_total{instance=~\"$Instance\"}[$__interval])[1m:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Column processing failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " avg_over_time(increase(beacon_data_column_sidecar_processing_requests_total{instance=~\"$Instance\"}[$__interval])[1m:]) -  avg_over_time(increase(beacon_data_column_sidecar_processing_successes_total{instance=~\"$Instance\"}[$__interval])[1m:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runtime of data column sidecars gossip verification",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_column_sidecar_gossip_verification_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_column_sidecar_gossip_verification_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 requests",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 requests to an execution layer",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_engine_getBlobsV2_requests_total{instance=~\"$Instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "engine_getBlobsV2 responses",
   "type": "timeseries",
   "description": "Total number of engine_getBlobsV2 successful responses from an execution layer",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_engine_getBlobsV2_responses_total{instance=~\"$Instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful engine_getBlobsV2 request rate (%)",
   "type": "timeseries",
   "description": "Percentage of engine_getBlobsV2 requests that did not receive a successful (not null) response",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by(instance)(increase(beacon_engine_getBlobsV2_requests_total{instance=~\"$Instance\"}[$__interval]))\n-\nsum by(instance)(increase(beacon_engine_getBlobsV2_responses_total{instance=~\"$Instance\"}[$__interval]))) / sum by(instance)(increase(beacon_engine_getBlobsV2_requests_total{instance=~\"$Instance\"}[$__interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime of engine_getBlobsV2",
   "type": "timeseries",
   "description": " Full runtime of engine_getBlobsV2",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_engine_getBlobsV2_request_duration_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(beacon_engine_getBlobsV2_request_duration_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custody groups (full nodes)",
   "type": "timeseries",
   "description": "Total number of custody groups for full nodes",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "beacon_custody_groups{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Custody groups (super nodes)",
   "type": "timeseries",
   "description": "Total number of custody groups for super nodes",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "beacon_custody_groups{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backfilled custody groups (super nodes)",
   "type": "timeseries",
   "description": "Total number of backfilled custody groups for super nodes",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "beacon_custody_groups_backfilled{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backfilled custody groups (full nodes)",
   "type": "timeseries",
   "description": "Total number of backfilled custody groups for full nodes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "beacon_custody_groups_backfilled{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Verification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Runtime of single data column kzg verification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_kzg_verification_data_column_single_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": " histogram_quantile(0.99, rate(beacon_kzg_verification_data_column_single_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of single data column kzg verifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  increase(\n    beacon_kzg_verification_data_column_single_seconds_count{instance=~\"$Instance\"}[$__interval]\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time taken to verify data column sidecar inclusion proof",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_column_sidecar_inclusion_proof_verification_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_column_sidecar_inclusion_proof_verification_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of calls to verify data column sidecar inclusion proof",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  increase(\n    beacon_data_column_sidecar_inclusion_proof_verification_seconds_count{instance=~\"$Instance\"}[$__interval]\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runtime of batched data column kzg verification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_kzg_verification_data_column_batch_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": " histogram_quantile(0.99, rate(beacon_kzg_verification_data_column_batch_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Reconstructions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Reconstruction duration counting from slot start",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(RECONSTRUCTION_DURATION_SINCE_SLOT_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total count of reconstructed columns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(beacon_data_availability_reconstructed_columns_total{instance=~\"$Instance\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of reconstructions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  increase(\n    beacon_data_availability_reconstruction_time_seconds_count{instance=~\"$Instance\"}[$__interval]\n  )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time taken to reconstruct columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_availability_reconstruction_time_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_availability_reconstruction_time_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reconstruction times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "COLUMN_RECONSTRUCTION_TIMES{instance=~\"$Instance\"} ",
     "legendFormat": "{{instance}} - {{blob_count}} blobs"
    }
   ]
  },
  { "title": "Compute cells", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Time taken to compute data column sidecar",
   "type": "timeseries",
   "description": "Time taken to compute data column sidecar, including cells and inclusion proof",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_column_sidecar_computation_seconds_bucket{instance=~\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{blob_count}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(beacon_data_column_sidecar_computation_milliseconds_bucket{instance=~\"$Instance\"}[$__rate_interval])) / 1000",
     "legendFormat": "{{instance}} {{blob_count}}"
    }
   ]
  },
  {
   "title": "Number of calls to compute data column sidecars",
   "type": "timeseries",
   "description": "Number of calls to compute data column sidecar, including cells and inclusion proof",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  increase(\n    beacon_data_column_sidecar_computation_seconds_count{instance=~\"$Instance\"}[$__interval]\n  )\n)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  { "title": "Gossipsub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Number of gossip messages sent to each topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(gossipsub_topic_msg_sent_counts_total{instance=~\"$Instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gossip messages received from each topic (including duplicates)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(gossipsub_topic_msg_recv_counts_unfiltered_total{instance=~\"$Instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gossip messages received from each topic (deduplicated)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(gossipsub_topic_msg_recv_counts_total{instance=~\"$Instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes sent to each topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(gossipsub_topic_msg_sent_bytes_total{instance=~\"$Instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes received from each topic (including duplicates)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(gossipsub_topic_msg_recv_bytes_unfiltered_total{instance=~\"$Instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of bytes received from each topic (deduplicated) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(gossipsub_topic_msg_recv_bytes_total{instance=~\"$Instance\", hash=~\".*/data_column_sidecar.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/Resp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 142 },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_requests_sent_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 142 },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_requests_received_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of responses sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 142 },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_responses_sent_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of responses received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 142 },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_responses_received_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests bytes sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_requests_bytes_sent_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of requests bytes received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_requests_bytes_received_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of responses bytes sent",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_responses_bytes_sent_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of responses bytes received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (increase(libp2p_rpc_responses_bytes_received_total{instance=~\"$Instance\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}