{
 "title": "Pools",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Attestation Agg pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Single attestation tracking times",
   "type": "timeseries",
   "description": "measure await times for attestation votes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ATT_POOL_ATTESTATION_TRACKING_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ATT_POOL_ATTESTATION_TRACKING_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insert attestation task",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ATT_POOL_INSERT_ATTESTATION_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ATT_POOL_INSERT_ATTESTATION_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "Attestation Packer iterations per slot",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(ATT_POOL_PACK_ITERATIONS{instance=~\"$Instance\"}[12s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Committee Contribution Agg pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Add own contribution task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(SYNC_POOL_ADD_OWN_CONTRIBUTION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(SYNC_POOL_ADD_OWN_CONTRIBUTION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "Aggregate own message task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(SYNC_POOL_AGGREGATE_OWN_MESSAGES_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(SYNC_POOL_AGGREGATE_OWN_MESSAGES_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Handle external contribution task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(SYNC_POOL_HANDLE_EXTERNAL_CONTRIBUTION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(SYNC_POOL_HANDLE_EXTERNAL_CONTRIBUTION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Handle external message task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(SYNC_POOL_HANDLE_EXTERNAL_MESSAGE_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(SYNC_POOL_HANDLE_EXTERNAL_MESSAGE_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Handle slot task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(SYNC_POOL_HANDLE_SLOT_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(SYNC_POOL_HANDLE_SLOT_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Collection Lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"operation_pools::sync_committee_agg_pool::pool\"}",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  { "title": "Bls to Execution change pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Discard old Bls To Execution changes task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BLS_POOL_DISCARD_OLD_CHANGES_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BLS_POOL_DISCARD_OLD_CHANGES_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Handle external Bls To Execution change task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BLS_POOL_HANDLE_EXTERNAL_CHANGE_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BLS_POOL_HANDLE_EXTERNAL_CHANGE_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Collection lengths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Block producer collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"block_producer::block_producer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eth1 chain collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"eth1::eth1_chain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fork choice mutator collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"fork_choice_control::mutator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fork choice store collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"fork_choice_store::store\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liveness tracker collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"liveness_tracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block sync service collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"p2p::block_sync_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Range and root requests collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"p2p::range_and_root_requests\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync manager collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"p2p::sync_manager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator collection lengths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "COLLECTION_LENGTHS{instance=~\"$Instance\",module=\"validator::validator\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}