{
 "title": "Proposal metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Validator proposal metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VALIDATOR_PROPOSE_SUCCESSES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(VALIDATOR_PROPOSE_SUCCESSES{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator propose tick times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(VALIDATOR_PROPOSE_TICK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_PROPOSE_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "VALIDATOR_PROPOSE_TIMES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_PROPOSE_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_PROPOSE_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slashing protector block proposal checking times (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(VALIDATOR_PROPOSAL_SLASHING_PROTECTOR_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_PROPOSAL_SLASHING_PROTECTOR_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "BUILD_BEACON_BLOCK_TIMES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BUILD_BEACON_BLOCK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BUILD_BEACON_BLOCK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Execution Payload times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(LOCAL_EXECUTION_PAYLOAD_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(LOCAL_EXECUTION_PAYLOAD_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Block Processing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BLOCK_TRANSITION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BLOCK_TRANSITION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Attestation Pool proposable attestation task times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ATT_POOL_PACK_PROPOSABLE_ATTESTATION_TASK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ATT_POOL_PACK_PROPOSABLE_ATTESTATION_TASK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Prepare BLS to Execution Changes times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(PREPARE_BLS_TO_EXECUTION_CHANGES_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(PREPARE_BLS_TO_EXECUTION_CHANGES_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Process sync committee contribution times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(PROCESS_SYNC_COMMITTEE_CONTRIBUTION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(PROCESS_SYNC_COMMITTEE_CONTRIBUTION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Eth1 Pending deposits times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ETH1_PENDING_DEPOSITS_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ETH1_PENDING_DEPOSITS_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Eth1 vote times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ETH1_VOTES_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ETH1_VOTES_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Prepare Voluntary Exits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(PREPARE_VOLUNTARY_EXIT_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(PREPARE_VOLUNTARY_EXIT_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Prepare Attester slashing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(PREPARE_ATTESTER_SLASHINGS_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(PREPARE_ATTESTER_SLASHINGS_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Prepare proposer slashing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(PREPARE_PROPOSER_SLASHINGS_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(PREPARE_PROPOSER_SLASHINGS_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  }
 ]
}