{
 "title": "Remote API",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  { "title": "ETH1 API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETH1 API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ETH1_API_REQUEST_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(ETH1_API_REQUEST_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{method}} ({{instance}})"
    }
   ]
  },
  {
   "title": "ETH1 API errors ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ETH1_API_ERRORS_COUNT{instance=~\"$Instance\"}"
    },
    {
     "expr": "ETH1_API_RESET_COUNT{instance=~\"$Instance\"}"
    }
   ]
  },
  { "title": "Web3Signer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Load keys ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(WEB3SIGNER_LOAD_KEYS_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(WEB3SIGNER_LOAD_KEYS_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Sign",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(WEB3SIGNER_SIGN_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(WEB3SIGNER_SIGN_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  { "title": "Builder API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Post Blinded Block",
   "type": "timeseries",
   "description": "Builder API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BUILDER_POST_BLINDED_BLOCK_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BUILDER_POST_BLINDED_BLOCK_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Register Validators",
   "type": "timeseries",
   "description": "Builder API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BUILDER_REGISTER_VALIDATORS_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BUILDER_REGISTER_VALIDATORS_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Get Execution Payload Header",
   "type": "timeseries",
   "description": "Builder API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BUILDER_GET_EXECUTION_PAYLOAD_HEADER_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BUILDER_GET_EXECUTION_PAYLOAD_HEADER_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  }
 ]
}