{
 "title": "Ticks",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  {
   "title": "Validator tick delays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "TICK_DELAY_TIMES{instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator propose tick delays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "TICK_DELAY_TIMES{tick=\"Propose\",instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator attest tick delays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "TICK_DELAY_TIMES{tick=\"Attest\",instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator aggregate tick delays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "TICK_DELAY_TIMES{tick=\"Aggregate\",instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}