{
 "title": "Traces & Spans",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service name",
    "query": {}
   },
   {
    "name": "slot",
    "label": "Slot",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Unaccounted root spans",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "fcbcd2a5", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "grandine-web3signer" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ nestedSetParent<0 && .service.name = \"grandine-web3signer\" && name != \"DataColumnSidecarTask::run\" && name != \"handle_tick\" && name != \"AttestationTask::run\" && name != \"StateAtSlotCacheFlushTask::run\" && name != \"RetryDataColumnSidecarTask::run\" && name != \"BlockAttestationTask::run\" && name != \"handle_head_message\" && name != \"prepare_execution_payload\" && name != \"PreprocessStateTask::run\" && name != \"PersistPubkeyCacheTask::run\" && name != \"CheckpointStateTask::run\" && name != \"on_requested_block\" && name != \"on_gossip_block\" && name != \"handle_voluntary_exit\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "service = \"validator\" ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "d4d6b08d", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "grandine-web3signer" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service_name\" && span.service = \"validator\" && traceDuration > 50ms} with (most_recent=true)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Built-in validator loop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.service=\"validator\" && .service.name = \"$service_name\" } | quantile_over_time(duration, .1) by (resource.service.name) with(exemplars=true)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Data Column Sidecars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ name=\"DataColumnSidecarTask::run\" && .service.name = \"$service_name\" } | quantile_over_time(duration, 0.01) by (resource.service.name) with(exemplars=true)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Block import metrics from spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ name=\"BlockTask::run\" && .service.name = \"$service_name\" && span.slot =~ \"$slot\" } | quantile_over_time(duration, .1) by (resource.service.name) with(exemplars=true)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Block imports",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "limit": 100,
     "metricsQueryType": "range",
     "query": "\n{resource.service.name=\"$service_name\" && (name=\"on_requested_block\" || name=\"on_api_block\" || name=\"on_own_block\" || name=\"on_gossip_block\") && span.slot =~ \"$slot\"} with (most_recent = true)",
     "tableType": "traces"
    }
   ]
  }
 ]
}