{
 "title": "Transition functions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Validator Epoch processing avg times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(VALIDATOR_EPOCH_PROCESSING_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(VALIDATOR_EPOCH_PROCESSING_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Generic Transitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block processing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BLOCK_TRANSITION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BLOCK_TRANSITION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "Blinded block processing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(BLINDED_BLOCK_TRANSITION_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(BLINDED_BLOCK_TRANSITION_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])\n"
    }
   ]
  },
  {
   "title": "Process Epoch times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(EPOCH_PROCESSING_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(EPOCH_PROCESSING_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Process Slots times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(PROCESS_SLOT_TIMES_sum{instance=~\"$Instance\"}[$__rate_interval]) / rate(PROCESS_SLOT_TIMES_count{instance=~\"$Instance\"}[$__rate_interval])"
    }
   ]
  }
 ]
}