[project]
name = "security-agents"
version = "0.2.0"
description = "Multi-phase security analysis using specialized AI agents"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.0.0",
    "openai-agents>=0.1.0",
    "python-dotenv>=1.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = [
    "main", 
    "parameter",
    "utils"
]