[package]
name = 'zkvm_pico_helper'
version = "0.1.0"
edition = { workspace = true }
authors = ["Grandine <info@grandine.io>"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }

[features]
