name: CI Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install OpenSSL (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        vcpkg install openssl:x64-windows-static-md
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
    - uses: Swatinem/rust-cache@v2
    - name: Check if code is formatted (Linux)
      if: runner.os == 'Linux'
      run: cargo fmt --check
    - name: Run Clippy
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          bash scripts/ci/clippy.bash --deny warnings
        elif [ "$RUNNER_OS" == "Windows" ]; then
          powershell.exe -ExecutionPolicy Bypass -File ./scripts/ci/clippy.ps1 --deny warnings
        fi
    - name: Run tests
      run: cargo test --release --no-fail-fast
    - name: Check consensus-spec-tests coverage (Linux)
      if: runner.os == 'Linux'
      run: scripts/ci/consensus-spec-tests-coverage.rb