name: CI Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Disable autocrlf (Windows)
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
    - uses: Swatinem/rust-cache@v2
    - name: Check if code is formatted (Linux)
      if: runner.os == 'Linux'
      run: cargo fmt --check
    - name: Run Clippy (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: bash scripts/ci/clippy.bash --deny warnings
    - name: Run tests
      run: cargo test --release --no-fail-fast
    - name: Check consensus-spec-tests coverage (Linux)
      if: runner.os == 'Linux'
      run: scripts/ci/consensus-spec-tests-coverage.rb