name: zkvm Test

on: [push]

jobs:
  zkvm-test:
    strategy:
      matrix:
        test_case: [
          # These two test cases can be completed in a reasonably short time
          "consensus spec tests mainnet electra empty block transition",
          "pectra-devnet-6 without epoch transition"
        ]

    runs-on: ubuntu-latest
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 1024
    - name: Setup nim for constantine backend
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.0.2'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        parent-nim-install-directory: ${{ runner.temp }}
    - name: Install dependencies for constantine backend
      run: |
        sudo DEBIAN_FRONTEND='noninteractive' apt-get install \
          --no-install-recommends -yq \
          libgmp-dev \
          llvm
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true

    - name: Install r0vm
      run: |
        curl -L https://risczero.com/install | bash
        /home/runner/.risc0/bin/rzup install cargo-risczero 3.0.1

    - name: Test zkvm-risc0
      run: RUST_LOG=info RISC0_DEV_MODE=1 cargo run -p zkvm_host --features risc0 --release -- --test "${{ matrix.test_case }}" execute

    - name: Install SP1
      run: |
        curl -L https://sp1up.succinct.xyz | bash
        /home/runner/.sp1/bin/sp1up -v 5.2.1 -- token ${{ secrets.GITHUB_TOKEN }}

    - name: zkvm-sp1
      run: RUST_LOG=info cargo run -p zkvm_host --features sp1 --release -- --test "${{ matrix.test_case }}" execute

    - name: Install Brevis Pico
      run: |
        rustup install nightly-2025-08-04
        rustup component add rust-src --toolchain nightly-2025-08-04
        cargo +nightly-2025-08-04 install --git https://github.com/brevis-network/pico pico-cli

    - name: zkvm-pico
      run: RUST_LOG=info cargo +nightly-2025-08-04 run -p zkvm_host --features pico --release -- --test "${{ matrix.test_case }}" execute
